services:
  vinted-monitor:
    image: ghcr.io/richrdj/vinted-scraper:latest
    pull_policy: always
    container_name: vinted-monitor
    ports:
      - "8344:8344"
    volumes:
      - vinted_data:/app/data
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      # Optioneel — alles is ook in de webinterface in te stellen:
      # WEB_USERNAME: admin
      # WEB_PASSWORD: geheim
      # TELEGRAM_ENABLED: "true"
      # TELEGRAM_TOKEN: "123456:ABC..."
      # TELEGRAM_CHAT_ID: "12345678"
      # NTFY_ENABLED: "true"
      # NTFY_TOPIC: "mijn-geheime-topic"
      # QUERY_REFRESH_DELAY: "60"

volumes:
  vinted_data:
